### ISSUE TITLE
scenes?

### ISSUE THREAD

**Issue by tigrazone** [HummaWhite/Vulkan-ReSTIR-PT#2]
Hello.
I built exe and started it.
Program fails with message
[Scene res/model/VeachAjar/ajar_fake2.xml]
[Error:Scene: failed to load]

Can you add this scene to repository?
Or add link where to get it

**Comment by HummaWhite** [comment]
Hi,
I added the scene

**Comment by tigrazone** [comment]
Thank you. But renderer stopped after scene read and show some statistics. Maybe absense of textures or something else. I dont debug deeply

**Comment by HummaWhite** [comment]
> Thank you. But renderer stopped after scene read and show some statistics. Maybe absense of textures or something else. I dont debug deeply

Hi, I realized there was a blank texture missing. Fixed.

**Comment by yubinZhouFW** [comment]
![image](https://github.com/user-attachments/assets/d62abdc4-a321-4352-87a0-069659343cfd)
can not extract the scene files
